name: Deploy Terraform to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: shivraj-chari/terraform-az-common-workflow/.github/workflows/terraform-deployment.yml@master
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
